cuisine_plus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('bookings/', include('bookings.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

handler404 = "cuisine_plus.views.page_not_found_view"

home/urls.py
from django.urls import path
from home.views import Home

urlpatterns = [
    path('', Home, name='Home'),
]

restaurants/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (MenuList, ReservationDeleteView, ReservationList,
                    ReservationUpdateView, RestaurantDetail, RestaurantLike,
                    RestaurantList)

urlpatterns = [
    path(
        'restaurant_list.html/',
        RestaurantList.as_view(),
        name='restaurants'
        ),

    path(
        'restaurant_detail/<pk>',
        login_required(RestaurantDetail.as_view()), name='restaurant_detail'
        ),

    path(
        'restaurant_detail.html',
        RestaurantList.as_view(),
        name='restaurant'
        ),

        path(
        'like/<pk>',
        RestaurantLike.as_view(),
        name="restaurant_like"
    ),

    path(
        'reservation_list.html/',
        ReservationList.as_view(),
        name='reservation'
        ),

    path(
        'restaurants/edit_reservation/<pk>',
        ReservationUpdateView.as_view(),
        name='edit'
        ),

    path(
        'delete_reservation/<pk>',
        ReservationDeleteView.as_view(),
        name='delete'
        ),

    path(
        'menu_list.html/',
        MenuList.as_view(),
        name='menu'
        ),
]

bookings/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField
from restaurants.models import Restaurant
# from cuisine.models import Cuisine

class Booking(models.Model):
    '''Booking model
    ---
    Attributes:
        user: User that made the booking
        number_of_guests: Number of guests expected
        restaurant: Name of the restaurant being booked
        cuisine: Menu of being booked
        table_number: Table number
        date: Date of the booking
        time: Time of the booking
        additional_info: Any additional information provided

    '''

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=False, related_name='bookings'
        )
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    phone = PhoneField(blank=True, help_text='Contact phone number')
    email = models.EmailField(null=True)
    number_of_guests = models.IntegerField()
    restaurants = models.ForeignKey(
        Restaurant, on_delete=models.CASCADE, related_name='bookings'
        )
    cuisine = models.CharField(max_length=100) 
    table_number = models.IntegerField(null=True, blank=True)
    date = models.DateField()
    time = models.TimeField()
    additional_info = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return str(self.last_name)
    

restaurants/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.db import models
from multiselectfield import MultiSelectField
from phone_field import PhoneField


class Restaurant(models.Model):
    '''Restaurant model
    ---
    Attributes:
        name: Name of the restaurant
        reserve: Reservations made by guests
        avg_rating: Average number of ratings by customers
        location: Address of restaurant
        featured_image: Photo image of the restaurant

    '''

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=False,
        related_name='restaurants'
        )
    name = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100)
    description = models.TextField(max_length=1500, null=True)
    likes = models.ManyToManyField(
        User, related_name='restaurant_likes', blank=True
    )
    CUISINE_TYPES = (
        (1, 'African'),
        (2, 'Chinese'),
        (3, 'Asian'),
        (4, 'Irish'),
        (5, 'Continental')
    )
    cuisine = MultiSelectField(choices=CUISINE_TYPES, max_choices=5, max_length=5, null=True)

    OPERATION_HOURS = (
        (1, '11:00am - 08:00pm'),
        (2, '12:00am - 08:00pm'),
        (3, '12:00am - 10:00pm'),
        (4, '01:00pm - 09:00pm'),
        (5, '03:00pm - 09:00pm'),
        (6, '03:00pm - 10:00pm'),
    )
    time = models.PositiveSmallIntegerField(choices=OPERATION_HOURS, null=True)
    featured_image = CloudinaryField()

    def __str__(self):
        return str(self.name)

    def number_of_likes(self):
        return self.likes.count()


class Menu(models.Model):
    '''Menu model
    ---
    Attributes:
        name: Name of the menu
        menu: Details of the food to be served
        price: Price of the menu
        menu_image: Photo image of the menu
        created_on: Date and time created
        updated_on: Date and time updated

    '''

    restaurants = models.ForeignKey(
        Restaurant, on_delete=models.CASCADE, related_name='menus'
    )
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(max_length=3500, null=True)
    body = models.TextField(max_length=2500, null=True)
    price = models.FloatField()
    menu_image = CloudinaryField('image', default='placeholder')

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return str(self.name)


class Review(models.Model):
    '''Review model
    ---
    Attributes:
        name: Name of the reviewer
        body: Customer comments
        created_on: Date and time created
        approved: Approval status

    '''

    restaurants = models.ForeignKey(
        Restaurant, on_delete=models.CASCADE, null=True, related_name='reviews'
    )
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField(max_length=250, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Review {self.body} by {self.name}"


class Reservation(models.Model):
    '''Reservation model
    ---
    Attributes:
        name: Name of the person that made the booking
        number_of_guests: Number of guests expected
        restaurant: Name of the restaurant being booked
        table_number: Table number
        date: Date of the booking
        time: Time of the booking
        additional_info: Any additional information provided
    '''

    restaurants = models.ForeignKey(
        Restaurant,
        on_delete=models.CASCADE,
        null=True,
        related_name='reservations'
    )
    name = models.CharField(max_length=100)
    phone = PhoneField(blank=True)
    number_of_guests = models.IntegerField()
    table_number = models.IntegerField(null=True, blank=True)
    date = models.DateField()
    time = models.TimeField()
    additional_info = models.TextField(max_length=150, null=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
    )

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return str(self.name)

restaurants/forms.py
from django.forms import ModelForm
from django import forms
from .models import Restaurant, Review, Reservation, Menu
from datetime import datetime


class RestaurantForm(ModelForm):
    class Meta:
        model = Restaurant
        fields = [
            'name',
            'address',
            'featured_image',
        ]


class MenuForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Write a menu List'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Describe the menu'}))

    class Meta:
        model = Menu
        fields = [
            'name',
            'description',
            'body',
            'price',
        ]


class ReviewForm(ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Write a Review'}))

    class Meta:
        model = Review
        fields = [
            'body',
        ]


class ReservationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}))
    number_of_guests = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Number of Guests'}))
    date = forms.DateField(
        initial=datetime.now().strftime("%Y-%m-%d"), 
        widget=forms.widgets.DateInput(attrs={
            'type': 'date', 
            'class': 'form-control', 
            'placeholder': 'Enter Date'
            }))

    time = forms.TimeField(widget=forms.TimeInput(attrs={
        'type': 'time', 
        'class': 'form-control', 
        'placeholder': 'Enter Time'
        }))
       
    additional_info = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control', 
        'rows': 5, 
        'placeholder': 'Your Comments'
        }))

    class Meta:
        model = Reservation
        fields = [
            'name',
            'number_of_guests',
            'date',
            'time',
            'additional_info'
        ]

    def __init__(self, *args, **kwargs):
        super(ReservationForm, self).__init__(*args, **kwargs)
        self.fields['number_of_guests'].widget.attrs['min'] = 1

restaurants/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import generic, View
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, DeleteView
from restaurants.models import Restaurant, Review, Reservation, Menu
from .forms import ReviewForm, ReservationForm, MenuForm
from bookings.forms import BookingForm
from bookings.models import Booking


class RestaurantList(generic.ListView):
    model = Restaurant
    queryset = Restaurant.objects.all()
    template_name = 'restaurants/restaurant_list.html'
    pagination = 4


class RestaurantDetail(generic.DetailView):

    model = Restaurant

    def get(self, request, *args, **kwargs):
        restaurant = Restaurant.objects.get(pk=kwargs["pk"])
        reviews = Review.objects.filter(restaurants=restaurant, approved=True)
        reservations = Reservation.objects.filter(restaurants=restaurant)
        menus = Menu.objects.filter(restaurants=restaurant)
        liked = False
        if restaurant.likes.filter(id=self.request.user.id).exists():
            liked = True

        context = {
            'restaurant': restaurant,
            'reviews': reviews,
            'reviewed': False,
            'reservations': reservations,
            'menus': menus,
            'bookings': Booking,
            'liked': liked,
            'review_form': ReviewForm(),
            'menu_form': MenuForm(),
            'reservation_form': ReservationForm(),
            'booking_form': BookingForm(),
        }

        return render(
            request,
            'restaurants/restaurant_detail.html',
            context)

    """
    Post data to database
    """
    # --- Review and Reservation view ---
    def post(self, request, pk, *args, **kwargs):
        restaurant = Restaurant.objects.get(id=request.POST.get("restaurant"))
        reviews = Review.objects.filter(restaurants=restaurant, approved=True)
        reservation_form = ReservationForm(data=request.POST)
        liked = False
        if restaurant.likes.filter(id=self.request.user.id).exists():
            liked = True

        if reservation_form.is_valid():
            reservation = reservation_form.save(commit=False)
            reservation.email = request.user.email
            reservation.name = request.user.username
            reservation.restaurants = restaurant
            reservation_form.save()
            messages.success(
                request, "Your reservation successfully submitted"
                )
            return HttpResponseRedirect(request.path_info)
        else:
            reservation_form = ReservationForm()

        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            review_form.instance.email = request.user.email
            review_form.instance.name = request.user.username
            review = review_form.save(commit=False)
            review.restaurants = restaurant
            review.save()
            messages.success(
                request, "Your review successfully submitted, but awaiting approval"
                )
            return HttpResponseRedirect(reverse('restaurant_detail', args=[pk]))
        else:
            review_form = ReviewForm()

        menu_form = MenuForm(data=request.POST)
        if menu_form.is_valid():
            menu.email = request.user.email
            menu.name = request.user.username
            menu = menu_form.save(commit=False)
            menu.restaurants = restaurant
            menu_form.save()
            return redirect('/')
        else:
            menu_form = MenuForm()

        return render(
            request,
            "restaurants/restaurant_detail.html",
            {
                'restaurant': Restaurant,
                'reviews': reviews,
                'reviewed': True,
                'liked': liked,
                "reservation_form": ReservationForm(),
            },
        )


class MenuList(generic.ListView):
    model = Menu
    queryset: Restaurant.objects.all()
    template_name = 'restaurants/menu_list.html'
    pagination = 8


class ReservationList(generic.ListView):
    model = Reservation
    queryset: Restaurant.objects.all()
    template_name = 'restaurants/reservation_list.html'
    pagination = 8

#  --- Reservation Update ---


class ReservationUpdateView(UpdateView):
    model = Reservation
    form_class = ReservationForm
    template_name = 'restaurants/edit_reservation.html'
    success_url = '/'

    def success(request):
        return render(request, '/')


class ReservationDeleteView(DeleteView):
    model = Reservation
    template_name = 'restaurants/delete_reservation.html'
    success_url = reverse_lazy('reservation')


class RestaurantLike(View):
    def post(self, request, pk, *args, **kwargs):
        restaurant = get_object_or_404(Restaurant, pk=pk)
        if restaurant.likes.filter(id=self.request.user.id).exists():
            restaurant.likes.remove(request.user)
        else:
            restaurant.likes.add(request.user)
        return HttpResponseRedirect(reverse('restaurant_detail', args=[pk]))

restaurants/templates/restaurants/datepicker.html
{% include "django/forms/widgets/input.html" %}

<script>
  $(function () {
    $("input[name='{{ widget.name }}']").datepicker({
      format:'dd/mm/yyyy',
    });
  });
</script>

restaurants/templates/restaurants/delete_reservation.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Delete Reservation {% endblock %}

{% block content %}

{% if user.is_authenticated %}
<div class="pt-5"></div>
<div class="card mx-auto" style="width: 30rem;">
    <div class="card-body">
        <div class="card-header text-center">
          <div class="text-center">
            <form method="POST">
                {% csrf_token %}
                <h4>{{ user|capfirst }}, are you sure you want to delete your booking?</h4>
                <p>Your booking and its related items will be deleted.</p>
                <div>
                    <p>
                        <a href="{% url 'reservation' %}" class="btn btn-secondary">No, take me back</a>
                        <button type="submit" class="btn btn-danger">Yes, I'm Sure</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

{% endif %}
{% endblock %}

restaurants/templates/restaurants/restaurant_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load cloudinary %}  

{% block content %}
{% if user.is_authenticated %}
<div class="masthead pb-4">
    <div class="container-fluid">
        <div class="row">
          <div >
            <img class="img-restaurant-detail" src="{{ restaurant.featured_image.url }}">            
          </div>
        </div>
    </div>
    <div class="container-fluid">
      <div class="row">
          <div class="col">
            <a href="{% url 'restaurant_detail' restaurant.pk %}" >
              <span class="card-title font-weight-bold"><strong>{{ restaurant.name }}</strong></span>
            </a> |
            <span class="card-text small"><i class="fa-solid fa-bowl-rice" aria-hidden="true"></i> {{ restaurant.get_cuisine_display }}</span> |
            <!-- Likes and number of likes  -->
            <strong>
              {% if user.is_authenticated %}
              <form class="d-inline" action="{% url 'restaurant_like' restaurant.pk %}" method="POST">
                {% csrf_token %}

                {% if liked %}
                <button type="submit" name="restaurantlike_id" value="{{ restaurant.pk }}" class="btn-like">
                  <i class="fas fa-heart" aria-hidden="true"></i>
                </button>

                {% else %}
                <button type="submit" name="restaurantlike_id" value="{{ restaurant.pk }}" class="btn-like">
                  <i class="far fa-heart" aria-hidden="true"></i>
                </button>

                {% endif %}

              </form>
              {% else %}
              <span class="card-text small"><i class="far fa-heart" aria-hidden="true"></i></span> 
              {% endif %}

              <span class="card-text small">{{ restaurant.number_of_likes }}</span> |
            </strong>
            <!-- Reviews and review count  -->
            <span class="card-text small"><i class="far fa-comments" aria-hidden="true"></i>{{ restaurant.review }}</span>
          </div>
      </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row border-end">
    
    <!-- togglebar -->
    <div class="col-sm-12">
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Overview</button>
          <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Reviews</button>
          <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Menu</button>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">

        <!-- Overview tab -->
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          <div class="container border-end"><br>
            <div class="row ">
              <!-- Restaurant Overview -->
              <div class="col-6">
                <h5 class="card-title">About {{ restaurant.name }}</h5>
                  {{ restaurant.description | safe }}
                <div class="row">
                  <div class="col-6">
                    <div class="card-body">
                        <div class="reviews" style="padding: 10px;">
                          <h5><i class="fa-solid fa-location-dot" aria-hidden="true"></i> <strong>Address:</strong> {{ restaurant.address }}</h5>                           
                        </div>
                    </div>
                  </div>
                  <div class="col-6 ">
                    <p><i class="fa-solid fa-bowl-rice" aria-hidden="true"></i> <strong>Cuisines:</strong> {{ restaurant.get_cuisine_display }}</p>
                    <p><i class="fa-regular fa-clock" aria-hidden="true"></i> <strong>Open Hours:</strong> {{ restaurant.get_time_display }}</p>
                    <p><i class="fa-solid fa-phone" aria-hidden="true"></i> <strong>Phone Numbers:</strong> {{ restaurant.phone }} </p>
                  </div>
              </div>
              </div>
              <!-- Booking form -->
              <div class="col-6">
                  <div class="card mx-auto" style="width: 25rem;">
                    <div class="card-body">
                        <div class="card-header text-center">
                            <h3 class="card-title">Make a Booking</h3>
                          </div><br>
                          <div class="text-center">
                            <form method="POST" id="id_date">
                              <input type="hidden" name="restaurant" value="{{ restaurant.pk }}">
                                {% csrf_token %}
                                {{ reservation_form.as_p }}
                                {{ crispy_forms | crispy }}
                                <div>
                                    <button type="submit" style="width: 22rem;" class="btn btn-primary">Confirm Reservation</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div> 
                </div>
            </div>
          </div>
        </div>

        <!-- Review tab -->
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
          <div class="container">
            <div class="row">
              <div class="col-8">
                <div class="card-body">
                  <br>
                  <h5><strong>Customer Reviews:</strong></h5>
                  <hr>
                    {% for review in reviews %}
                    <div class="reviews" style="padding: 10px;">
                        <p class="font-weight-bold">
                            <span class=" text-muted font-weight-normal">
                              Wrote on: {{ review.created_on | date:"D, d M Y" }},
                              {{ review.created_on | time:"H:ia" }}
                            </span> 
                        </p>
                        "{{ review.body }}" - {{ review.name }}
                        
                    </div><br><hr>
                    {% empty %}
                    <div>
                      <p>No customer reviews yet for this restaurant.</p>
                      <span>Be the first to write a review</span>
                    </div>
                    {% endfor %}
                </div>
              </div>
              <div class="col-4 border-end text-center">
                <!-- Reviews form -->
              <div class="review-form" style="width: 25rem;">
                <div class="card-body">
                    {% if reviewed %}
                    <div class="alert alert-success" role="alert">
                      {{ user.username }}, your review is awaiting approval
                    </div>
                    {% else %}
                    <h5><strong>Review this Restaurant:</strong></h5>
                    <p>Share your thoughts with other customers</p>
                    <p>Reviewing as: {{ user.username }}</p>
                    <form method="POST">
                      <input type="hidden" name="restaurant" value="{{ restaurant.pk }}">
                        {% csrf_token %}
                        {{ review_form.as_p}}
                        {{ crispy_forms | crispy }}
                      <div>
                          <button type="submit" style="width: 23rem;" class="btn btn-primary">Submit</button>
                      </div>
                    </form>
                </div>
              </div>                  
              </div>
            </div>
          </div>
        </div>

        <!-- Menu tab -->
        {% for menu in menus %}
        <div class="container-fluid">
          <div class="tab-pane fade " id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
            <div class="border-end">
              <!-- Bootstrap tab with vertical message  -->
              <div class="d-flex align-items-start">
                <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                  <button class="nav-link" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">Food</button>
                  <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">Drinks</button>
                </div>
                <div class="tab-content" id="v-pills-tabContent">
                  <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">                  
                    <div class="accordion" id="accordionPanelsStayOpenExample">
                      <!-- First Accordion  -->
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Menu Image
                          </button>
                        </h2>
                        <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                          <div class="accordion-body">
                            <div class="reviews" style="padding: 10px;">
                              <p class="font-weight-bold">
                                <img class="img-restaurant-detail" src="{{ menu.menu_image.url }}">
                              </p>
                          </div>
                          <div>{{ menu.body | safe }}</div>
                          </div>
                        </div>
                      </div>
                       <!-- Second Accordion  -->
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                            Menu Description
                          </button>
                        </h2>
                        <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                          <div class="accordion-body">
                            <div><strong>Menu</strong></div> 
                            <div>Served Mon-Fri from <strong>{{ restaurant.get_time_display }}</strong></div>
                            {{ menu.description | safe }}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock %}

restaurants/templates/restaurants/restaurant_list.html
{% extends 'base.html' %}

{% block content %}
{% load cloudinary %}  

{% if user.is_authenticated %}

<div class="container-fluid">
    <div class="row">
        <div class="hero-image pt-5 text-center" >   
        </div>
    </div>
    <div class="row">
        <div class="col-12 mt-3 left restaurant-list">
            <div class="row">
                <h6>Featured Restaurants <span>&raquo;</span></h6>
                {% for restaurant in restaurant_list %}
                <div class="col-md-3">
                    <div class="shadow-sm card mb-2">
                        <div class="card-body mb-2" >
                            <div class="image-container">
                                {% if "placeholder" in restaurant.image.url %}
                                <img class="card-img-top"
                                    src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                                {% else %}
                                <img class="card-img-top img-restaurant-list" src="{{ restaurant.featured_image.url }}" alt="Restaurant image">
                                {% endif %}
                            </div>
                            <a href="{% url 'restaurant_detail' restaurant.pk %}" class="text-decoration-none"> 
                                <span class="card-title font-weight-bold"><strong>{{ restaurant.name }}</strong></span>
                                <span class="card-text small link-dark"><i class="fa-solid fa-location-dot" aria-hidden="true"></i> {{ restaurant.address }}</span><br>
                                <span class="card-text small text-muted"><i class="fa-solid fa-clock" aria-hidden="true"></i> {{ restaurant.get_time_display }}</span><br>
                                <span class="card-text small text-muted"><i class="fa-solid fa-bowl-rice" aria-hidden="true"></i> {{ restaurant.get_cuisine_display }}</span><br>
                            </a>
                                <span class="card-text small text-muted"><i class="fa-solid fa-heart" aria-hidden="true"></i> {{ restaurant.like }}</span>
                                <span class="card-text small">{{ restaurant.number_of_likes }}</span><br>
                                <span class="card-text small"><i class="far fa-comments" aria-hidden="true"></i>{{ restaurant.review }} Reviews</span>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>   
        </div>
    </div>
    {% if is_paginated %}
   
    <!-- Standard "pagination" code from Django ListView  -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endif %}
{% endblock %}