bookings/urls.py
from django.urls import path
from .views import BookingList, BookingUpdateView, BookingCreateView, BookingDeleteView

urlpatterns = [
    path(
        'bookings/booking_detail.html', 
        BookingList.as_view(), 
        name='booking_detail'
        ),

    # --- self ---
    path(
        'booking.html', 
        BookingCreateView.as_view(success_url="booking.html"), 
        name='booking_create'
        ),
    # --- self end ----

    path(
        'list', 
        BookingList.as_view(), 
        name='booking'
        ),
    
    
    path(
        'edit_booking/<pk>', 
        BookingUpdateView.as_view(), 
        name='edit'
        ),
    
    path(
        'delete_booking/<pk>', 
        BookingDeleteView.as_view(), 
        name='delete'
        ),
]

cuisine_plus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('bookings/', include('bookings.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

handler404 = "cuisine_plus.views.page_not_found_view"

home/urls.py
from django.urls import path
from home.views import Home

urlpatterns = [
    path('', Home, name='Home'),
]

bookings/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField
from restaurants.models import Restaurant
# from cuisine.models import Cuisine

class Booking(models.Model):
    '''Booking model
    ---
    Attributes:
        user: User that made the booking
        number_of_guests: Number of guests expected
        restaurant: Name of the restaurant being booked
        cuisine: Menu of being booked
        table_number: Table number
        date: Date of the booking
        time: Time of the booking
        additional_info: Any additional information provided

    '''

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=False, related_name='bookings'
        )
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    phone = PhoneField(blank=True, help_text='Contact phone number')
    email = models.EmailField(null=True)
    number_of_guests = models.IntegerField()
    restaurants = models.ForeignKey(
        Restaurant, on_delete=models.CASCADE, related_name='bookings'
        )
    cuisine = models.CharField(max_length=100) 
    table_number = models.IntegerField(null=True, blank=True)
    date = models.DateField()
    time = models.TimeField()
    additional_info = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return str(self.last_name)
    

bookings/forms.py
from django.forms import ModelForm
from .models import Booking


class BookingForm(ModelForm):
    class Meta:
        model = Booking
        fields = [
            'first_name',
            'last_name',
            'number_of_guests',
            'date',
            'time',
            'phone',
            'additional_info',
            ]
        

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Booking
from .forms import BookingForm
from django.urls import reverse_lazy


class BookingList(generic.ListView):
    model = Booking
    template_name = 'bookings/booking_detail.html'

    context = {
        'bookings': Booking.objects.all()
    }
   
    """
    Get data from forms.py and render in booking_form
    """

    def get(self, request, *args, **kwargs):
        print(self, request, args, kwargs)

        bookings = Booking.objects.all()
       
        return render(
            request, 
            "bookings/booking_detail.html", 
            {
                "booking_form": BookingForm(),
                "bookings": bookings,
                }
        )

    """
    Post data to database 
    """

    def post(self, request):

        if request.method == 'POST':
            booking_form = BookingForm(request.POST)
            if booking_form.is_valid():
                booking = booking_form.save(commit=False)
                booking.booking_form = booking_form
                booking.save()
                return redirect('/')
            else:
                booking_form = BookingForm()

        return render(
            request, 
            "bookings/booking_detail.html", 
            {
                "booking_form": BookingForm()
            }
        )

 
class BookingCreateView(CreateView):
    model = Booking
    form_class = BookingForm
    template_name = 'bookings/booking.html'
    queryset = Booking.objects.all()

    def get_object(self):
        return get_object_or_404('')


class BookingUpdateView(UpdateView):
    model = Booking
    form_class = BookingForm
    template_name = 'bookings/edit_booking.html'
    success_url = '/'

    def success(request):
        return render(request, '/')


class BookingDeleteView(DeleteView):
    model = Booking
    template_name = 'bookings/delete_booking.html'
    success_url = reverse_lazy('booking')

bookings/templates/bookings/booking.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
<div>
 
    <h1>
        Booking Your Cuisine
    </h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        {{ crispy_forms | crispy }}
        <input type="submit" class="btn btn-primary" value="Submit"> 
    </form>
</div>

{% endif %}
{% endblock %}

bookings/templates/bookings/booking_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block content %}

{% if user.is_authenticated %}
<div class="card mx-auto text-center" style="width: 18rem;">
    <div class="card-body">
        {% for booking in bookings %}
        <div class="card-header">
            <h5 class="card-title">Your Booking Detail:</h5>
          </div>
        <p class="card-text">First Name: {{ booking.first_name }}</p>
        <p class="card-text">Last Name: {{ booking.last_name }}</p>
        <p class="card-text">No. of Guests: {{ booking.number_of_guests }}</p>
        <p class="card-text">Date: {{ booking.date }}</p>
        <p class="card-text">Time: {{ booking.time }}</p>
        <p class="card-text">Phone: {{ booking.phone }}</p>
        <p class="card-text">Additional Info: {{ booking.additional_info }}</p>
        <div class="btn-group btn-group-justified">
            <a href="{% url 'edit' booking.pk %}" class="btn btn-info">Edit</a>
            <a href="{% url 'delete' booking.pk %}" class="btn btn-danger">Delete</a>
        </div>
        <hr> 
        {% endfor %}
    </div>
</div>

{% endif %}
{% endblock %}

bookings/templates/bookings/booking_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block content %}

{% if user.is_authenticated %}
<div class="col-sm-4">
    {% for booking in bookings %}
        <p>{{ booking.first_name }}</p>
        <p>{{ booking_form.as_p }}</p>
        <a href="{% url 'edit' booking.pk %}"><button class="btn btn-primary" formaction="">Edit</button></a>
        <a href="{% url 'edit' booking.pk %}"><button class="btn btn-primary" formaction="">Delete</button></a>
    {% endfor %}
{% else %}

    <h1>
        Booking Form or a new form
    </h1>

    <form method="POST" action="{% url 'booking' %}">
        {% csrf_token %}
        {{ booking_form.as_p }}
        <div class="col-sm-4">
        </div>
        <input type="submit" value="Submit">
        <a href=""><button class="btn btn-primary" formaction="">Edit Booking</button></a> 
    </form>
</div>



<div>
    <h1>
        Book a Table
    </h1>
</div>

<div>
    {% for booking in booking_list %}
    {{booking.user}}
    {{booking.restaurant}}
    {% endfor %}
    
</div>

{% endif %}

<script type="text/javascript">
    $(function() {
        $('#datepicker').datepicker();
    });
</script>
{% endblock %}

bookings/templates/bookings/confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Delete Booking {% endblock %}



{% block content %}

{% if user.is_authenticated %}

<div class="card mx-auto" style="width: 30rem;">
    <div class="card-body">
     
        <div class="card-header text-center">
          <div class="text-center">
            <form method="POST">
                {% csrf_token %}
                <h4>{{ booking }}, are you sure you want to delete your booking?</h4>
                <p>Your booking and its related items will be deleted.</p>
                <div>
                    <p>
                        <button type="submit" class="btn btn-primary">No, take me back</button>
                        <button type="submit" class="btn btn-danger">Yes, I'm Sure</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

{% endif %}
{% endblock %}

bookings/templates/bookings/create_booking.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
<div>
 
    <h1>
        Booking Form
    </h1>

    <form method="POST" action="{% url 'create_booking' %}">
        {% csrf_token %}
        {{ booking_form.as_p }}
        <input type="submit" value="Submit">
    </form>

</div>

{% else %}

<div>
    <h1>
        Sign Up or Login to Book a Table
    </h1>
</div>

<div>
    {% for booking in booking_list %}
    {{booking.user}}
    {{booking.restaurant}}
    {% endfor %}
    
</div>
{% endif %}
{% endblock %}

bookings/templates/bookings/delete_booking.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Delete Booking {% endblock %}



{% block content %}

{% if user.is_authenticated %}

<div class="card mx-auto" style="width: 30rem;">
    <div class="card-body">
     
        <div class="card-header text-center">
          <div class="text-center">
            <form method="POST">
                {% csrf_token %}
                <h4>{{ booking }}, are you sure you want to delete your booking?</h4>
                <p>Your booking and its related items will be deleted.</p>
                <div>
                    <p>
                        <a href="{% url 'booking' %}" class="btn btn-info">No, take me back</a>
                        <button type="submit" class="btn btn-danger">Yes, I'm Sure</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

{% endif %}
{% endblock %}

bookings/templates/bookings/edit_booking.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block content %}

{% if user.is_authenticated %}

<div class="card mx-auto" style="width: 30rem;">
    <div class="card-body">
     
        <div class="card-header text-center">
            <h3 class="card-title">Edit Your Booking</h3>
          </div><br>
          <div class="text-center">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button type="submit" class="btn btn-secondary">Cancel</button>
                    <button type="submit" class="btn btn-primary">Edit Booking</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% else %}

<div>
    <h1>
        You must be a registered user to access this page
    </h1>
</div>

{% endif %}

{% endblock %}